image: Visual Studio 2019

environment:
  matrix:
  - PYTHON: Python36
  - PYTHON: Python37
  - PYTHON: Python38
  - PYTHON: Python39
  - PYTHON: Python310

install:
- SET PATH=C:\\%PYTHON%;%PATH%
- python --version
- python -m pip install colorama

build: off

test_script:
- python appfoyer .

# vim:ts=2 sts=2 sw=2 et
