environment:
  matrix:
  - PYTHON: Python33
  - PYTHON: Python34
  - PYTHON: Python35
  - PYTHON: Python36

install:
- SET PATH=C:\\%PYTHON%;%PATH%
- python --version
- python -m pip install colorama

build: off

test_script:
- python appfoyer .

# vim:ts=2 sts=2 sw=2 et
