dist: trusty
language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
branches:
  except:
  - appveyor
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
install:
- python3 -m pip install colorama
- python3 -m pip install pydiatra $pyflakes
- python3 -m pip install restructuredtext-lint
script:
- ./appfoyer .
- python3 -m pyflakes .
- python3 -m pydiatra .
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
