dist: trusty
sudo: false
language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
install:
- pip install docutils
- pip install pydiatra pyflakes
script:
- ./trava .
- python3 -m pyflakes trava lib/*.py
- python3 -m pydiatra trava lib/*.py
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
