dist: trusty
sudo: false
language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
install:
- pip install pydiatra pyflakes
- pip install restructuredtext-lint
script:
- ./trava .
- python3 -m pyflakes trava lib/*.py
- python3 -m pydiatra trava lib/*.py
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
