dist: xenial
language: python
jobs:
  include:
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "3.9-dev"
branches:
  except:
  - appveyor
before_install:
- colorama=colorama
- if [[ $TRAVIS_PYTHON_VERSION = 3.4 ]]; then colorama+='<0.4'; fi
install:
- python3 -m pip install $colorama
- python3 -m pip install pydiatra pyflakes
- python3 -m pip install restructuredtext-lint
script:
- python3 -m pyflakes .
- python3 -m pydiatra .
- restructuredtext-lint --encoding=UTF-8 README
- export PYTHONWARNINGS=d
- ./appfoyer .

# vim:ts=2 sts=2 sw=2 et
