name: CI
on:
  push:
    branches-ignore:
    - appveyor
  pull_request:
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '3.4'
          os: ubuntu-18.04
        - python: '3.5'
          os: ubuntu-18.04
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-20.04
        - python: '3.11-dev'
          os: ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: install deps
      run: |
        colorama=colorama
        if [[ ${{matrix.python}} = 3.4 ]]; then colorama+='<0.4.2'; fi
        python3 -m pip install $colorama
    - name: smoke test
      run: |
        ./appfoyer .
      env:
        PYTHONWARNINGS: d
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint
        rst-lint --level=info --encoding=UTF-8 README
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .

# vim:ts=2 sts=2 sw=2 et
